all:
  children:
    ansible:
      hosts:
        localhost:
          ansible_connection: local
          ansible_user: "ubuntu"
          hostname: AnsibleMaster
          ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
    dev:
      hosts:
        worker01: 
          ansible_host: "{{ host_var_ip }}"
          hostname: AnsibleWorker01
          ansible_user: "ubuntu"
      vars:
        env: "developpement"
        ansible_ssh_common_args: "-o StrictHostKeyChecking=no"